### ISSUE TITLE
Colors in progress bars

### ISSUE THREAD

**Issue by saltysir** [b3nj5m1n/enhancemainwindowthemes#1]
these are awesome! I ended up changing some of the colors from the lime tempelate, but failed to find where to change the colours in the bars. Do you happen by any chance to know how to change them? The total progress -bar has two almost same shades of green, and i'd like to add some contrast to it

**Comment by b3nj5m1n** [comment]
Hi, either download one of the finished themes, or clone the repository, change the template and then rebuild the themes. You're going to have to change the colors of the individual sections on the progress bars, first of all you define what should be in the progress bar,
```json
        {
            "description": "Percent bar to do today",
            "header": "<p style='color: #1E6823'>Progress Today</p>",
            "name": "bar",
            "names": [
                "review today",
                "learning card",
                "new today",
                "reviewed today"
            ],
            "overlay": null,
            "present": true,
            "subdeck": true
        },
```
then you define the colors used for the individual sections, so if you wanted to change the color representing "new today", you'd look for this section:
```json
        {
            "absolute": true,
            "color": "#5CAE4C",
            "description": "Unseen cards you will see today (what Anki calls New cards). Neither buried nor suspended.",
            "header": "<p style='color: #1E6823'>New</p>",
            "name": "new today",
            "overlay": null,
            "percent": false,
            "present": true,
            "subdeck": true
        },
```
and then change the "color" attribute.

Hope that I could help you, and glad you enjoy my templates.

**Comment by saltysir** [comment]
yes! that helped, found the right one. Thank you!
