### ISSUE TITLE
Cannot change main window font color

### ISSUE THREAD

**Issue by MedBlueprint** [b3nj5m1n/enhancemainwindowthemes#2]
hello dear :)
Loved your anki add on but I cannot change the Main Window decks,subdecks name text color in the add on settings.
could you please tell /provide a guideline on how can I do that?

**Comment by b3nj5m1n** [comment]
Just to clarify, have you successfully installed the "enhance main window" add-on and put one of the configs in the add-on's config, and now want to customize the color of deck names?

**Comment by MedBlueprint** [comment]
yes. 
1. installed & put flame simplified configs in the add-on's config
2. now I want to change the RED color of deck name texts to WHITE(marked in  image)
![image](https://user-images.githubusercontent.com/75526224/105450755-5a57e100-5ca5-11eb-86a9-a32984408aef.png)

**Comment by b3nj5m1n** [comment]
@MedBlueprint Open up the add-on config again, you'll need to edit 2 fields, they're called "color empty" and "color empty descendant" (They should be at the very top), simply edit the values of those fields.
Here's an example:
```
{
    "book symbol": "{",
    "cap value": null,
    "color empty": "#ff0066",
    "color empty descendant": "#ff0066",
    "color zero": true,
...
```
That will make the colour of the deck names pink.
